
#General configurations for More Plates
[General]
	#Set this to false to disable all crafting recipes for Gears
	enable_gear = true
	#Set this to false to disable all crafting recipes for Plates
	enable_plate = true
	#Set this to false to disable all crafting recipes for Rods
	enable_rod = true
	#Hammer Durability
	#Range: > 1
	hammer_durability = 150

#Item configurations for More Plates
[Items]
	#Enable vibranium integration
	register_vibranium = false
	#Enable crystaltine integration
	register_crystaltine = true
	#Enable netherite integration
	register_netherite = true
	#Enable ivory psimetal integration
	register_ivory_psimetal = true
	#Enable emerald integration
	register_emerald = true
	#Enable tungsten carbide integration
	register_tungsten_carbide = false
	#Enable prudentium integration
	register_prudentium = false
	#Enable unobtainium all the modium alloy integration
	register_unobtainium_allthemodium_alloy = true
	#Enable manasteel integration
	register_manasteel = true
	#Enable compressed iron integration
	register_compressed_iron = true
	#Enable the ultimate integration
	register_the_ultimate = true
	#Enable malachite integration
	register_malachite = true
	#Enable aquamarine integration
	register_aquamarine = true
	#Enable black iron integration
	register_black_iron = true
	#Enable glowstone integration
	register_glowstone = true
	#Enable bronze integration
	register_bronze = true
	#Enable prosperity integration
	register_prosperity = false
	#Enable silver integration
	register_silver = true
	#Enable platinum integration
	register_platinum = true
	#Enable tungsten integration
	register_tungsten = false
	#Enable supremium integration
	register_supremium = false
	#Enable prismarine integration
	register_prismarine_crystals = true
	#Enable quartz enriched iron integration
	register_quartz_enriched_iron = true
	#Enable imperium integration
	register_imperium = false
	#Enable sapphire integration
	register_sapphire = true
	#Enable refined glowstone integration
	register_refined_glowstone = true
	#Enable lumium integration
	register_lumium = true
	#Enable coal integration
	register_coal = true
	#Enable terrasteel integration
	register_terrasteel = true
	#Enable electrum integration
	register_electrum = true
	#Enable diamond integration
	register_diamond = true
	#Enable purple alloy integration
	register_purple_alloy = false
	#Enable soulium integration
	register_soulium = false
	#Enable neptunium integration
	register_neptunium = true
	#Enable certus quartz integration
	register_certus_quartz = true
	#Enable charcoal integration
	register_charcoal = true
	#Enable quartz integration
	register_nether_quartz = true
	#Enable red alloy integration
	register_red_alloy = false
	#Enable osmium integration
	register_osmium = true
	#Enable enhanced ender integration
	register_enhanced_ender = true
	#Enable fluix integration
	register_fluix = true
	#Enable vibranium all the modium alloy integration
	register_vibranium_allthemodium_alloy = true
	#Enable brass integration
	register_brass = false
	#Enable iron integration
	register_iron = true
	#Enable tin integration
	register_tin = true
	#Enable flint integration
	register_flint = true
	#Enable elementium integration
	register_elementium = true
	#Enable nickel integration
	register_nickel = true
	#Enable tertium integration
	register_tertium = false
	#Enable bismuth integration
	register_bismuth = true
	#Enable starmetal integration
	register_starmetal = true
	#Enable unobtainium integration
	register_unobtainium = false
	#Enable amethyst integration
	register_amethyst = true
	#Enable ruby integration
	register_ruby = true
	#Enable insanium integration
	register_insanium = false
	#Enable all the modium integration
	register_allthemodium = true
	#Enable ender integration
	register_ender = true
	#Enable enderium integration
	register_enderium = true
	#Enable nether brick integration
	register_nether_brick = true
	#Enable lead integration
	register_lead = true
	#Enable gold integration
	register_gold = true
	#Enable redstone ingot integration
	register_redstone_ingot = true
	#Enable resonating gem integration
	register_resonating_gem = true
	#Enable gaia spirit integration
	register_gaia_spirit = true
	#Enable uranium integration
	register_uranium = true
	#Enable signalum integration
	register_signalum = true
	#Enable zinc integration
	register_zinc = false
	#Enable refined obsidian integration
	register_refined_obsidian = true
	#Enable steel integration
	register_steel = true
	#Enable energized steel integration
	register_energized_steel = true
	#Enable copper integration
	register_copper = true
	#Enable psimetal integration
	register_psimetal = true
	#Enable blue alloy integration
	register_blue_alloy = false
	#Enable inferium integration
	register_inferium = false
	#Enable ebony psimetal integration
	register_ebony_psimetal = true
	#Enable brick integration
	register_brick = true
	#Enable invar integration
	register_invar = true
	#Enable lapis integration
	register_lapis_lazuli = true
	#Enable aluminum integration
	register_aluminum = true
	#Enable redstone integration
	register_redstone = true
	#Enable paper integration
	register_paper = true
	#Enable vibranium unobtainium alloy integration
	register_vibranium_unobtainium_alloy = false
	#Enable constantan integration
	register_constantan = true

